# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Brian Eng
tagline:          'Brian Eng – Product Growth Scientist'
description:      'Data scientist at Twitch'
url:              http://wukaiyuan.com
baseurl:          /

author:
  name:           'Brian Eng'
  url:            https://twitter.com/wukaiyuan

paginate:         5

# Custom vars
linkedin:         https://www.linkedin.com/in/brianheng

version:          1.0

github:
  repo:           https://github.com/wukaiyuan?tab=repositories
